version: 1.0.{build}
skip_branch_with_pr: true
image:
- Visual Studio 2019

build_script:
- ps: >-
    # Restore NuGets

    dotnet restore

    # Build

    dotnet build --configuration Release

    ## Publish

    .\publish.ps1

artifacts:
- path: artifacts\*.zip